version: '3.7'
services:
  emails-mongo:
    container_name: emails-mongo
    image: mongo:4
    restart: "no"
    ports:
      - 27017:27017
    environment:
      EMAILS_DB_PASSWORD: "${ADMIN_PASSWORD}"
      TZ: "Europe/Warsaw"
    volumes:
      - ./scripts/init_mongo.sh:/docker-entrypoint-initdb.d/init_mongo.sh:ro

  emails-rabbitmq:
    container_name: emails-rabbitmq
    image: rabbitmq:3-management
    restart: "no"
    ports:
      - 15672:15672
      - 5672:5672

  emails-api:
    container_name: emails-api
    image: jvmops/emails-api
    restart: "no"
    depends_on:
      - emails-mongo
      - emails-rabbitmq
    ports:
      - 8080:8080
    environment:
      SPRING_DATA_MONGODB_HOST: emails-mongo
      SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE: emails
      SPRING_DATA_MONGODB_USERNAME: api
      SPRING_DATA_MONGODB_PASSWORD: "${ADMIN_PASSWORD}"
      SPRING_RABBITMQ_HOST: emails-rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_JACKSON_DEFAULT-PROPERTY-INCLUSION: non_null

  emails-sender:
    container_name: emails-sender
    image: jvmops/emails-sender
    restart: "no"
    depends_on:
      - emails-mongo
      - emails-rabbitmq
    environment:
      SPRING_DATA_MONGODB_HOST: emails-mongo
      SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE: emails
      SPRING_DATA_MONGODB_USERNAME: sender
      SPRING_DATA_MONGODB_PASSWORD: "${ADMIN_PASSWORD}"
      SPRING_RABBITMQ_HOST: emails-rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_MAIL_USERNAME: changeme
      SPRING_MAIL_PASSWORD: changeme
